spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://host.docker.internal:5432/demo}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

server:
  port: 8080
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_KEY_STORE_PASSWORD:nydc11}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS:renderLadder}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

cors:
  # Development settings
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost,http://localhost:8080,https://localhost:8080,https://localhost:80,https://localhost:4200,https://192.168.1.158:4200,https://ladder-app-a4ra.onrender.com}
  allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
  allowed-headers: ${CORS_ALLOWED_HEADERS:*}
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
  max-age: ${CORS_MAX_AGE:3600}

services:
  backend:
    environment:
      - CORS_ALLOWED_ORIGINS=https://ladder-app-a4ra.onrender.com 