/*

DROP TABLE PLAYERS if exists;
DROP TABLE PLAYER if exists;
DROP TABLE LADDER if exists;
DROP TABLE PLAYER_LADDER if exists;
DROP TABLE SCORE if exists;
DROP TABLE COURT if exists;

CREATE TABLE PLAYER (PLAYER_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, FIRST_NAME varchar(25) NOT NULL, LAST_NAME varchar(25) NOT NULL,
                    COURT_ID INTEGER, EMAIL varchar(75), CELL varchar(15), LEVEL FLOAT, AVAILABILITY varchar(500), PASSWORD varchar(255));

CREATE TABLE LADDER (LADDER_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, Name varchar(75), START_DATE DATE, END_DATE DATE, COORDINATOR_ID INT);

CREATE TABLE PLAYER_LADDER (LADDER_ID INT NOT NULL, PLAYER_ID INT NOT NULL);

CREATE TABLE COURT (COURT_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, NAME varchar(75), ADDRESS varchar(255), LINK varchar(255), PHONE varchar(15));

INSERT INTO COURT (NAME, ADDRESS, PHONE, LINK) VALUES ('Padgetts', '7210 Allentown Road Fort Washington, MD', ' (301) 449-5566', 'https://www.pgparks.com/facilities/allentown-splash-tennis-and-fitness-park-aquatic-center');
INSERT INTO COURT (NAME, ADDRESS, PHONE, LINK) VALUES ('Cosca', '11000 Thrift Road Clinton, MD', '301-868-6462', 'https://www.pgparks.com/facilities/cosca-tennis-bubble');
INSERT INTO COURT (NAME, ADDRESS, PHONE, LINK) VALUES ('Watkins', '301 Watkins Park Drive Kettering, MD 20774', '301-218-6870', 'https://www.pgparks.com/facilities/watkins-tennis-bubble');
INSERT INTO COURT (NAME, ADDRESS, PHONE, LINK) VALUES ('Lake Arbor Park', '1100 Arbor Park Place Bowie, MD 20721', '', 'https://www.pgparks.com/parks_trails/arbor-park');
INSERT INTO COURT (NAME, ADDRESS, PHONE, LINK) VALUES ('Lake Arbor Golf Course', '1401 Golf Course Dr Mitchellville, MD 20721', '', '');
INSERT INTO COURT (NAME, ADDRESS, PHONE, LINK) VALUES ('Tucker Rd', '1771 Tucker Road, Fort Washington, MD 20744', ' (301) 248-4404','https://www.pgparks.com/facilities/tucker-road-community-center');
INSERT INTO COURT (NAME, ADDRESS, PHONE, LINK) VALUES ('Tanglewood Community Park', '8339 Woodyard Road, Clinton, MD 20735', ' (301) 699-2400','https://www.pgparks.com/parks_trails/tanglewood-park');
INSERT INTO COURT (NAME, ADDRESS, PHONE, LINK) VALUES ('Gwynn Park High School', '13800 Brandywine Road, Brandywine, MD 20613', ' 301-372-0140','https://www.pgcps.org/schools/gwynn-park-high');





---  Each row in MATCH_RESULT is for a match and there is only one row per match
CREATE TABLE MATCH_RESULT (MATCH_RESULT_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, MATCH_ID INT, PLAYER1_ID INT NOT NULL, PLAYER2_ID INT NOT NULL,
                           MATCH_WINNER_ID INT NOT NULL, MATCH_DATE TIMESTAMP NOT NULL);

---  Each row in SET_SCORE is for a player in a set, for each singles match there are either 4 or 6 rows in SET_SCORE
CREATE TABLE SET_SCORE (SET_SCORE_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, MATCH_RESULT_ID INT NOT NULL, PLAYER_ID INT NOT NULL,
                        SET_NUMBER INT NOT NULL, SET_SCORE INT NOT NULL, SET_WINNER INT NOT NULL);

*/   