-- =============================================================================
-- DOUBLES MATCH TRACKING DDL
-- =============================================================================
-- Design choice: separate doubles tables rather than adding nullable team
-- columns to the existing MATCH / MATCH_RESULT / SET_SCORE tables.
--
-- Rationale:
--   In singles, MATCH_RESULT.MATCH_WINNER_ID and SET_SCORE.PLAYER_ID reference
--   a PLAYER.  In doubles those same concepts must reference a DOUBLES_TEAM —
--   a different entity.  Mixing both into the same column (or adding parallel
--   nullable columns) produces mutually-exclusive "either/or" columns, which
--   weakens referential integrity and complicates every query.
--   Separate tables keep each schema fully defined, constraints unambiguous,
--   and existing singles code completely untouched.
--
-- DOUBLES_TEAM already exists in schema.sql:
--   DOUBLES_TEAM (DOUBLES_TEAM_ID PK, PLAYER1_ID, PLAYER2_ID)
--
-- New tables mirror the singles hierarchy:
--   DOUBLES_MATCH        ←→  MATCH
--   DOUBLES_MATCH_RESULT ←→  MATCH_RESULT
--   DOUBLES_SET_SCORE    ←→  SET_SCORE
--
-- Optional join table:
--   DOUBLES_TEAM_LADDER  ←→  PLAYER_LADDER
-- =============================================================================
CREATE TABLE DOUBLES_TEAM (DOUBLES_TEAM_ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
                           PLAYER1_ID INTEGER NOT NULL, PLAYER2_ID INTEGER NOT NULL);

-- -----------------------------------------------------------------------------
-- DOUBLES_TEAM_LADDER
-- Associates a doubles team with a ladder (mirrors PLAYER_LADDER for singles).
-- -----------------------------------------------------------------------------
CREATE TABLE DOUBLES_TEAM_LADDER (
    LADDER_ID       INTEGER NOT NULL,
    DOUBLES_TEAM_ID INTEGER NOT NULL,
    CONSTRAINT PK_DOUBLES_TEAM_LADDER PRIMARY KEY (LADDER_ID, DOUBLES_TEAM_ID),
    CONSTRAINT FK_DTL_LADDER FOREIGN KEY (LADDER_ID)       REFERENCES LADDER(LADDER_ID),
    CONSTRAINT FK_DTL_TEAM   FOREIGN KEY (DOUBLES_TEAM_ID) REFERENCES DOUBLES_TEAM(DOUBLES_TEAM_ID)
);


-- -----------------------------------------------------------------------------
-- DOUBLES_MATCH
-- A scheduled doubles match between two teams on a ladder (mirrors MATCH).
-- team1_id / team2_id reference DOUBLES_TEAM instead of individual players.
-- -----------------------------------------------------------------------------
CREATE TABLE DOUBLES_MATCH (
    DOUBLES_MATCH_ID        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LADDER_ID               INTEGER      NOT NULL,
    TEAM1_ID                INTEGER      NOT NULL,
    TEAM2_ID                INTEGER      NOT NULL,
    MATCH_DATE              TIMESTAMP(6) NOT NULL,
    COURT_ID                INTEGER      NOT NULL,
    MATCH_SCHEDULED_STATUS  VARCHAR(255),
    CONSTRAINT FK_DM_LADDER FOREIGN KEY (LADDER_ID) REFERENCES LADDER(LADDER_ID),
    CONSTRAINT FK_DM_TEAM1  FOREIGN KEY (TEAM1_ID)  REFERENCES DOUBLES_TEAM(DOUBLES_TEAM_ID),
    CONSTRAINT FK_DM_TEAM2  FOREIGN KEY (TEAM2_ID)  REFERENCES DOUBLES_TEAM(DOUBLES_TEAM_ID),
    CONSTRAINT FK_DM_COURT  FOREIGN KEY (COURT_ID)  REFERENCES COURT(COURT_ID),
    CONSTRAINT CHK_DM_TEAMS CHECK (TEAM1_ID <> TEAM2_ID)
);


-- -----------------------------------------------------------------------------
-- DOUBLES_MATCH_RESULT
-- The recorded outcome of a completed doubles match (mirrors MATCH_RESULT).
-- One row per match.  WINNING_TEAM_ID references the winning DOUBLES_TEAM.
-- -----------------------------------------------------------------------------
CREATE TABLE DOUBLES_MATCH_RESULT (
    DOUBLES_MATCH_RESULT_ID INTEGER   GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOUBLES_MATCH_ID        INTEGER   NOT NULL,
    TEAM1_ID                INTEGER   NOT NULL,
    TEAM2_ID                INTEGER   NOT NULL,
    WINNING_TEAM_ID         INTEGER   NOT NULL,
    MATCH_DATE              TIMESTAMP NOT NULL,
    LADDER_ID               INTEGER   NOT NULL,
    COURT_ID                INTEGER   NOT NULL,
    CONSTRAINT FK_DMR_MATCH   FOREIGN KEY (DOUBLES_MATCH_ID) REFERENCES DOUBLES_MATCH(DOUBLES_MATCH_ID),
    CONSTRAINT FK_DMR_TEAM1   FOREIGN KEY (TEAM1_ID)         REFERENCES DOUBLES_TEAM(DOUBLES_TEAM_ID),
    CONSTRAINT FK_DMR_TEAM2   FOREIGN KEY (TEAM2_ID)         REFERENCES DOUBLES_TEAM(DOUBLES_TEAM_ID),
    CONSTRAINT FK_DMR_WINNER  FOREIGN KEY (WINNING_TEAM_ID)  REFERENCES DOUBLES_TEAM(DOUBLES_TEAM_ID),
    CONSTRAINT FK_DMR_LADDER  FOREIGN KEY (LADDER_ID)        REFERENCES LADDER(LADDER_ID),
    CONSTRAINT FK_DMR_COURT   FOREIGN KEY (COURT_ID)         REFERENCES COURT(COURT_ID),
    CONSTRAINT CHK_DMR_WINNER CHECK (WINNING_TEAM_ID IN (TEAM1_ID, TEAM2_ID))
);


-- -----------------------------------------------------------------------------
-- DOUBLES_SET_SCORE
-- One row per team per set played (mirrors SET_SCORE, using TEAM_ID in place
-- of PLAYER_ID).  For a 3-set match there are 6 rows: 2 teams × 3 sets.
-- SET_WINNER = 1 if this team won the set, 0 if they lost.
-- -----------------------------------------------------------------------------
CREATE TABLE DOUBLES_SET_SCORE (
    DOUBLES_SET_SCORE_ID    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOUBLES_MATCH_RESULT_ID INTEGER NOT NULL,
    TEAM_ID                 INTEGER NOT NULL,
    SET_NUMBER              INTEGER NOT NULL,
    SET_SCORE               INTEGER NOT NULL,
    SET_WINNER              INTEGER NOT NULL,
    CONSTRAINT FK_DSS_RESULT FOREIGN KEY (DOUBLES_MATCH_RESULT_ID) REFERENCES DOUBLES_MATCH_RESULT(DOUBLES_MATCH_RESULT_ID),
    CONSTRAINT FK_DSS_TEAM   FOREIGN KEY (TEAM_ID)                  REFERENCES DOUBLES_TEAM(DOUBLES_TEAM_ID),
    CONSTRAINT CHK_DSS_WINNER CHECK (SET_WINNER IN (0, 1))
);
